channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - sympy
  - seaborn
  - pip
  - pip:
    - opencv-python
