channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - pandas
  - sympy
  - seaborn
  - opencv
  - python-graphviz
